# Experiment Configuration
experiment_name: "config_mating"

# Image Options
image_options:
    dimention: "TCWH" # Target dimension of the image (Time x Channel x Width x Height)
                    # If the input image original order does not follow this, change the order
    resolution:
        20220802_YAV2104xYAV2105_001:
            reso: 0.19440
            bin: 3
        20220813_YAV2104xYAV2105_002:
            reso: 0.12960
            bin: 2
        YAV2104xYAV2105_20220826:
            reso: 0.12960
            bin: 2
        YAV2104xYAV2105_005:
            reso: 0.12960
            bin: 2
        20220903_YAV2104xYAV2105_003:
            reso: 0.12960
            bin: 2
        20221215_vd_001:
            reso: 0.12960
            bin: 2
        20221225_vd_02:
            reso: 0.12960
            bin: 2
        20230105_vd_002:
            reso: 0.12960
            bin: 2
        20230315_h90:
            reso: 0.21660
            bin: 2

measure_options:
  contours_length: 60 # The number of resample points for one object's contours.
                      # This parameter defines how detailed the contour measurements will be.
                      # Higher values increase the granularity of the measurement.

tracker_options:
  feature_dimention: 8  # The number of feature points used to track a single object over time.
                        # This setting determines the complexity of the tracking algorithm.
                        # A higher number of points can improve tracking accuracy but may increase computational cost.
